In [33]:
import numpy as np
from collections import Counter
import os


NUM_CLASSES = 3
NUM_PAIR = 52
graph_per_video = 1
min_move_num = 50

for try_count in range(1, 6):
    predicts = np.load(f"{try_count}.pkl.npy")
    print(len(predicts))
    correct = 0
    confusion_matrix = np.zeros((3, 3))

    for i in range(NUM_CLASSES*NUM_PAIR): 
        # 投票
        a = predicts[(i)*(graph_per_video*min_move_num):(i+1)*(graph_per_video*min_move_num)]
        if i == 155:
            print(a)
        count = Counter(a)
        most_common_value = count.most_common(1)[0][0]

        confusion_matrix[i%3, most_common_value] += 1

        if most_common_value == (i % 3):
            correct += 1
                
    vote_acc =  100. * correct / (NUM_CLASSES*NUM_PAIR*graph_per_video)

    # os.makedirs(f"{try_count}", exist_ok=True)
    # np.save(f"{try_count}/conf_mat", confusion_matrix)
    # np.save(f"{try_count}/vote_acc", vote_acc)

    print(confusion_matrix)
    print('# vote : ', vote_acc)

7800
[1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 2]
[[36. 16.  0.]
 [24. 28.  0.]
 [ 4. 22. 26.]]
# vote :  57.69230769230769
15600
[1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 2]
[[36. 16.  0.]
 [24. 28.  0.]
 [ 4. 22. 26.]]
# vote :  57.69230769230769
23400
[1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 2]
[[36. 16.  0.]
 [24. 28.  0.]
 [ 4. 22. 26.]]
# vote :  57.69230769230769
31200
[1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 2]
[[36. 16.  0.]
 [24. 28.  0.]
 [ 4. 22. 26.]]
# vote :  57.69230769230769
39000
[1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 2 2 1 1 1 2 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 2]
[[36. 16.  0.]
 [24. 28.  0.]
 [ 4. 22. 26.]]
# vote :  57.69230769230769


In [ ]:
import joblib
import numpy as np

from utils.visualize import one_person_3d_video

# filename = ["up", "upper_right", "down", "lower_left"]

# for name in filename:
results = joblib.load(f"my_data/{name}.pkl")

frames = len(results)
keypoints = np.zeros([frames, 23, 3, 3])

for i, key in enumerate(results):
    keypoints[i] = results[key]["smpl"][0]['body_pose']
    # print(results[key]["camera"][0])

pp = [0, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
# keypoints = pre_normalization(keypoints)
one_person_3d_video(keypoints[:100, :, 1], filename=f'my_data/a', view=[90, 0], pp=pp)

In [ ]:
import numpy as np

data = np.load("my_data/rotation/1/data.npy")
print(data.shape)

for i in range(50):
    print(data[i, 0, 0, 0])